### ISSUE TITLE
Hacky crashes while parsing upvoted topic

### ISSUE THREAD

**Issue by dvbportal** [eliaskg/Hacky#10]
Today Hacky suddenly refuses to start. The crash happens when I am logged in into HN using Safari. The auth cookie seems to affect Hacky. When parsing an upvoted topic, there is no id (maybe due to the missing arrow). 

```
Printing description of topic:
{
    comments = 156;
    "created_at" = "5 hours ago";
    score = 166;
    title = "Docker - the Linux container runtime";
    url = "http://docker.io/";
    user = radimm;
}
```

setReadMarks fails at

```
 if ([defaults valueForKey:[topic valueForKey:@"id"]]) {
      [topic setValue:[NSNumber numberWithInt:1] forKey:@"isRead"]; 
```

**Comment by eliaskg** [comment]
Thanks for your report. Unfortunately I really can't reproduce your bug.
- I'm logged in to HN on Safari (which is my default browser)
- The story "Docker - the Linux container runtime" is still on my front page
- This story was upvoted by me

Still, Hacky works.

Is Hacky still crashing for you on the master branch just at the moment?

**Comment by dvbportal** [comment]
Hi, I am on master and its still crashing. Docker is not on the front page anymore, but I can still reproduce this with any other topic. Maybe it has something to do with my account. Can you think of any case that the parser does not find the id field? All other fields are filled. Anyways, if no one has this problem you can close this issue, because I have fixed it for me.

**Comment by eliaskg** [comment]
On what version do you run Hacky? (Menu: Hacky -> About)

**Comment by dvbportal** [comment]
I am on Version 1.1 (1.1)
