### ISSUE TITLE
Title bar dropdown reappears when dismissing by clicking elswhere

### ISSUE THREAD

**Issue by sjmulder** [eliaskg/Hacky#14]
Steps to reproduce:
1. Click the title bar dropdown in the title bar that initially says “Top”.
2. Click outside the popup, but inside the window.

Expected result: the popup is dismissed.

Actual result: the popup fades out and then immediately reappears.

Notes:
- Occurs in Hacky 2.0
- Does not occur when clicking outside of the Hacky window.
- Another workaround is selecting an item in the popup.

**Comment by eliaskg** [comment]
You're completely right and I'm able to reproduce the bug. Unfortunately by now I couldn't find a way to solve this. Any ideas are appreciated!

**Comment by eliaskg** [comment]
Awesome, thanks for the pull request! Code will be merged and available in the next update!

**Comment by sjmulder** [comment]
Thanks @rickyc!
