### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by johntdyer** [eliaskg/Hacky#25]
Hello,

 I am sorry, but I am not that familiar with Xcode apps, but I wanted to try to build yours from source.  You mentioned I have to remove the iCloud provisioning profile or install my own, however I am not sure how to remove the iCloud code from your app w/o breaking it.  Can you possibly give some steps to disable iCloud functionality in order for a user to build it  ?

**Comment by eliaskg** [comment]
You have to remove all information regarding the Provisioning Profile from the project setting. If you do so, Hacky will only use CoreData without trying to push to iCloud.

**Comment by johntdyer** [comment]
Great, thanks!
