### ISSUE TITLE
Enhancement: Pull to refresh

### ISSUE THREAD

**Issue by AaronMT** [eliaskg/Hacky#3]
It would be nice if instead of a refresh button there was pull-to-refresh (scroll down from top-article), akin to Tweetbot.

**Comment by eliaskg** [comment]
Agreed! :)

**Comment by eliaskg** [comment]
Its going to happen: https://vimeo.com/59241421

**Comment by eliaskg** [comment]
Feature implemented in the current version. Closing now.
