### ISSUE TITLE
"Zero Inbox" for Hacky

### ISSUE THREAD

**Issue by nerdbeere** [eliaskg/Hacky#36]
Hi,

I really enjoy using this little tool. I purchased it over the App Store and now I am curious if it would be possible to add a "zero inbox" like feature.
It would be super awesome if I could just hide all read articles.

Julian

**Comment by eliaskg** [comment]
Thanks for the idea. As this is a duplicate issue as https://github.com/eliaskg/Hacky/issues/20 I will close this.
