### ISSUE TITLE
Crashlytics doesn't accept new registrations?

### ISSUE THREAD

**Issue by frdmn** [eliaskg/Hacky#38]
Hello, 

I just tried to setup a new account at Crashlytics apparently they disabled the registration. All I could do is enter an invite code:

![bildschirmfoto 2013-11-05 um 13 41 12](https://f.cloud.github.com/assets/944459/1473332/944aebca-4617-11e3-9fd7-36803cb12c68.png)

I used the URL out of the Xcode console (https://api.crashlytics.com/api/v1/[...]/com.eliasklughammer.hackernews).

Thanks,
Jonas

**Comment by eliaskg** [comment]
Crashlytics for Mac OS apps is currently in private beta. Just remove the Crashlytics stuff from the app and it should build properly.

**Comment by frdmn** [comment]
Thanks.

—
