### ISSUE TITLE
Suggestion: HNKit

### ISSUE THREAD

**Issue by grp** [eliaskg/Hacky#4]
I figured I'd plug my own stuff here, since you can easily close the issue.

For my iOS client for Hacker News, I've written a whole Objective-C framework that can handle everything from scraping Hacker News to rendering comments with Core Text, as well as persisting them in an offline object database. It's pretty simple and shouldn't have any issues on the Mac.

One of the big advantages of it is that it doesn't require any server-side scraping, and so you don't ever have an issue with the aggressive Hacker News rate limiting.

If you want to check it out, the code is here (BSD licensed): https://github.com/Xuzz/newsyc/tree/master/Classes/HNKit

Let me know if you have any questions!

**Comment by eliaskg** [comment]
Hi Paul!

Thanks for the hint! I looked into HNKit but it provides way too much functionality than I need at this point. I built a very basic HN scraper myself which will be included in the next version. (Also I wanted to learn html scraping in Objective-C ;)

By the way, I am one of your happy customers who uses news:yc many many times a day for quite a long time now! Keep up the good work!

Cheers!
