### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by lardissone** [eliaskg/Hacky#8]
Hi,

I've posted on HN these features but just in case I mirror them here:

-Native social sharing (Twitter/Facebook)
-Save to Pocket
-Display URL in each post (at least domain name)
-Easy way to mark as read each item (example: if you highlight item, it should be marked as read)
-Vim keyboard navigation (hjkl)
-Menubar icon with unread count (optional)
-Preferences panel with options like: refresh period, mute specific words, etc

**Comment by noahlh** [comment]
Good suggestions!  I'll add one to the mix:
- Option to hide stories that are already read (vs. just showing them dimmed).

I've found that A) I love Hacky and B) I generally have it sitting off to the side of my screen and I read it kind of like email - when a notification of a new story pops up, I head over and quickly scan to see what it is.  However, often new stories appear near the bottom so I have to scroll through the list of top stories to see what's new.  

It'd be awesome if previously-read stories were simply not there, so new unread stories appeared much like email messages - right at the top of the queue.

**Comment by noahlh** [comment]
BTW this seems best done as a toggle of some sort (with a keyboard shortcut) - so users can quickly switch between "hide read stories" and not.

**Comment by lardissone** [comment]
I agree with the hide read stories. Makes no sense to keep them in the list, but it would be great to have the option to hide and show them again.

**Comment by eliaskg** [comment]
Good ideas! Vim keyboard navigation will be even included in the next update. A settings panel and some other pretty cool features are on its way!

**Comment by noahlh** [comment]
Awesome awesome awesome :+1: 

Thanks Elias!

**Comment by jschuur** [comment]
More feature suggestions that I also posted to HN originally:
- Growl/Notification center notices for new stories (optionally configurable by a certain points threshold).
- Subscribe to certain topics (keyword based searches). Only get notified when certain topics have stories.
- Ignore stories by user.
- Search (both locally and offer to use hnsearch.com)
- List new submissions (separate tab?).
- Comments/open hotkeys (previously mentioned here, I see).
- Minimize to Mac OS menu with an icon indicating new stories (follows your notification threshold and/or topic subscriptions).
- Tab to monitor your own submissions.

**Comment by noahlh** [comment]
Great suggestions.  Some more I just thought of, since we're designing our "dream HN app" here ;)
-  Karma tracking at the top of the app (similar to what's on HN - maybe at the top right next to the refresh button - your logged-in username and current karma).  Right clicking on that should give you a link to your user profile.
-  Some sort of notification (a la reddit's orangered envelope) for when you have new replies to your comments.  This would be genuinely useful as there's currently no way to know if people reply to you unless you manually go and check HN.

**Comment by lardissone** [comment]
Another feature to the list:
- Forever history, not only the latest 30. I was off for 4 days, and was hoping to catch up all these days news and, no luck.

**Comment by eliaskg** [comment]
Please use one issue per feature suggestion from now on. Closing the issue now.
